apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: livenesstestapp
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: livenessdemo
    server: 'https://kubernetes.default.svc'
  source:
    path: 0-Demo_Files/Liveness_Deployment
    repoURL: 'https://github.com/yugaa22/ArgoCD-Complete-Master-Course.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
