apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  annotations:
    argocd.argoproj.io/sync-options: Validate=true
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
  # Intentional Schema Validation Issue
  # The 'replicas' field is not valid for a Pod specification.
  

